name: walkwise
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.5
  supabase: ^2.0.0
  flutter_dotenv: ^5.2.1
  firebase_auth: ^4.17.5
  provider: ^6.1.4
  flashy_tab_bar2: ^0.0.10
  flutter_svg: ^2.0.9
  http: ^1.1.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  url_launcher: ^6.3.1
  timeago: ^3.2.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 400
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 500

